# Mercury2 HWM Device Configuration File
#
# This file contains the device configuration for the Mercury2 hardware manager. It specifies information about each 
# device available to the ground station such as the device ID, driver, and connection settings.
#
# See the provided documentation for a complete overview of the Mercury2 HWM configuration system.

# devices: An array that contains the configuration settings for all devices that the ground station has access to.
#
# At a minimum, each device entry must specify an id and driver. There is also an optional "settings" argument that can
# be used to specify connection settings and other arbitrary options that will be passed to the driver upon 
# initialization. For example:
#
# > devices:
# >   - id: "test_device"
# >     driver: "Test_Driver"
# >     settings:
# >       address: "127.0.0.1"
# >       port: "1234"
#
# Required: True
devices: []
